### PR TITLE
Update repack layout

### LINKED ISSUE #1873: Repack - UI tweaks
## Is your feature request related to a problem? Please describe 👀
Wondering about rearranging the UI items on the repack modal & form, to something like this:

Screenshot 2023-06-01 at 10 59 29 AM

With the table rows being within a fixed height area, with scroll-y auto to provide scroll if required.
Change the Ok to Save also perhaps.

### PR DESCRIPTION
**Pull request by mark-prins**
Fixes #1873 

# 👩🏻‍💻 What does this PR do? 
 
Rearranged the items and updated, as per Andrei's mock in #694 
Now calculating the resulting number of packs - am showing as 2d.p. so that it's obvious if you are being fractional or not. Hopefully that doesn't confuse people 🤷 

**No repacks yet**

Screenshot 2023-06-06 at 5 09 57 PM

**Viewing list of repacks**

Screenshot 2023-06-06 at 5 52 47 PM

**New repack**

Screenshot 2023-06-06 at 5 59 13 PM

**Viewing existing repack**

Screenshot 2023-06-06 at 5 58 53 PM

## 📃 Documentation

- [ ] Repacks feature needs adding

### CODE REVIEW

**Review by roxy-dao — COMMENTED** [review]
Looks good Mark~ Thanks.

The available number of packs doesn't update after you've done a repack and still shows the pre-repacked available number of packs >.<

**Comment by mark-prins** [comment]
> The packs available doesn't update after you've done a repack and still shows the pre-repacked number >.<

Good catch! thanks - that was in the back of my mind to check and forgot.
The issue with it is that the `stockLine` was being saved in state in the list component. Have changed this, so that it only stores the `id` now.

Have also tidied `!invoiceId` and made that into `isNew` to make the logic easier to read.

1588d91e0

**Review by roxy-dao — APPROVED** [review]
Thanks Mark~

nit: Can the "Select a line..." text be moved to before the table?
Screenshot 2023-06-07 at 10 00 59 AM

**Comment by mark-prins** [comment]
I've moved the text - have tried various places, I prefer having it below the button a little:

image

**Pull request merged**
