### PR TITLE
298 serial numbers

### LINKED ISSUE #298: Serial Numbers
We seem to be getting some duplicates, not sure if it's data file issue or sync issue, but it's much easier to reason about numbers (invoice, requisition, stocktake) by just using max number for type. Since we have a hard sync rule about record ownership, this shouldn't be an issue.

- [ ] Remove number table entirely
- [ ] Just use max serial number (by type) when creating new records

### PR DESCRIPTION
**Pull request by roxy-dao**
Closes #298

### CODE REVIEW

**Review by clemens-msupply — COMMENTED** [review]
Just thought a bit about race conditions. Sqlite has a transaction isolation level of SERIALIZABLE which means if a tx succeeds its like a single user accessed the DB -> all good. Postgres has a lower isolation level of READ COMMITTED which can lead to tx anomalies.

Already in the old code there was a bug in next_number. If two transaction run concurrently they could both start with same old number which would result in a number used twice. However, this can be fixed by using SELECT FOR UPDATE (see https://www.postgresql.org/docs/current/explicit-locking.html row level locks).

With the new way to calculate the number I am not sure if this would work, e.g. don't think it helps to lock the row with the highest number because two tx might have a different idea what this row is.

We can increase the isolation level for the particular tx but this would be quite complicated and would require us to handle retries if there is a concurrent number update.

We might need to lock the table in ACCESS EXCLUSIVE mode? I haven't worked with advisory locks but this might be a solution as well. @jmbrunskill do you have some knowledge about it?

**Comment by jmbrunskill** [comment]
I haven't read all the code or understand the full situation, but here's some thoughts.

1) Databases like postgres provide a `sequence` generator for purposes like this, they are multi user safe so we could generate the next invoice number using this. https://www.postgresql.org/docs/9.1/functions-sequence.html
It looks like postgres allows this sequence to be set to a particular number, so would allow us to say set it to the largest number seen after a sync or something if that's a requirement.

I remember Chris saying something about number-reuse where we fill in numbers that didn't get used? 
I hope this isn't still a requirement with open-mSupply?

2) Could we just use BigSerial for our invoice numbers? I haven't tried it but I'm pretty sure you can insert into a serial column without breaking the serial (e.g. for syncing the records.) Sqlite has autoincrement which would serve a similar purpose. To use this, if you have other records that need that value,  you'll need to get the serial number back from the db after an insert.

3) I agree an Exclusive lock or advisory lock is probably required if we want to ensure two concurrent queries can't get the same 'max' record. 

>  SELECT FOR UPDATE will wait for a concurrent transaction that has run any of those commands on the same row, and will then lock and return the updated row (or no row, if the row was deleted). 
https://www.postgresql.org/docs/current/explicit-locking.html

My read of this suggests both SELECT FOR UPDATE queries would return the same row.

Advisory locks look like they would probably work here we could create one for each `next_number` table. It would allow pure read transactions to succeed on the table, but reads that hold that lock 

We'd need to make sure the lock is acquired at the higher level transaction where the record is written, not just in the 'get max number' transaction, otherwise we could end up not fixing the problem at all.

I think a `Sequence` or `Serial` are probably the best solutions unless we have some business rules or constraint that would mean we need something more custom.

**Comment by jmbrunskill** [comment]
After reading the code a bit more I see the goal is to give a incrementing number for each store and type, so can't just use a serial or autoincrement if we need that constraint.

**Comment by jmbrunskill** [comment]
Advisory Locks sound like a good solution for postgres.
I guess we'd need to create a function that we call to set and unset the lock that is a no-op on sqlite. We wouldn't want to have postgres specific code leaking too deeply into the code base.

Pretty sure you can just start the transaction with this
`SELECT pg_advisory_xact_lock(123);` 

This should unlock when the transaction ends, which sounds like the safest way to do this.
We could probably use an enum for the lock_id (123 in this example), so we only lock the related record type (e.g 123 == invoice 124 == requisition).

Alternatively, we could probably have a number service in rust that gets initialised from the database on startup, and ensures non-concurrent access via a mutex, but I think that's unnecessarily complex.

**Comment by clemens-msupply** [comment]
Or just have one global Mutex serializing any number generation. Would avoid sqlite/postgres differences (and at least for me easier to understand, I am never 100% sure what is locked/safe in Postgres)

**Comment by jmbrunskill** [comment]
> Or just have one global Mutex serializing any number generation. Would avoid sqlite/postgres differences (and at least for me easier to understand, I am never 100% sure what is locked/safe in Postgres)

Agreed, we'd just need to hold the mutex till the database write is completed, or decouple the number generation from the database `max` query.

**Comment by andreievg** [comment]
I've made an issue to discuss concurrency problem: https://github.com/openmsupply/open-msupply/issues/442

**Review by andreievg — APPROVED** [review]
This looks good to me, 🤞 we won't need to reinstate number table, I think if we do it won't be for these types anyways, it would be for new 'arbitrary' types

**Comment by andreievg** [comment]
@roxy-dao can you hold of merging please, there is a solution to possible concurrency issue, and it involves number table..

**Comment by andreievg** [comment]
@roxy-dao sorry, i did this to you again, we want to keep this table since there is a new requirement of custom serial number for programs (and also row locking seems like the best way to avoid serial number conflicts), I've updated this [issue](https://github.com/openmsupply/open-msupply/issues/442) to describe a solution that solve the data discrepancy between number table and invoices, it will be done as part of sync/initialisation (i'll have to do it into features/sync-v5 branch).

**Pull request closed without merging**
