### PR TITLE
Region-specific language variants

### LINKED ISSUE #1513: Rename 'Spanish (Colombia)' to 'Spanish' in translations
## Is your feature request related to a problem? Please describe 👀

@yeisonportela has translated a large portion of 'Spanish (Colombia)' and has used formal Spanish throughout. 

So it would be good to use this as the master translation for the Spanish language. 

I was thinking the easiest way would probably be to just swap the names between the two Spanish translations - although I'm sure there will be a catch...

image

### PR DESCRIPTION
**Pull request by mark-prins**
Closes #1513, #951

# 👩🏻‍💻 What does this PR do? 
 
Moved the Spanish translations to a Colombian regional language set: `es-CO`
Also added a Djibouti variant of French while I was at it.

image

image

# 🧪 How has/should this change been tested? 

You can check by changing to French ( which has the euro currency symbol ) and Djibouti French which has `DJF` and calls outbound shipments `Bon Command` instead of `Livraison Sortante`

## 📃 Documentation

- [ ] A screenshot of language options?

### CODE REVIEW

**Comment by adamdewey** [comment]
Oh, I've potentially confused things in #1513 

We wanted the translation work that Yeison has done so far to be the main 'Español' in the app and for 'Español (Colombia)' to be removed for now

P.s. there's no `a` on the end of 'Español' 😆

**Comment by mark-prins** [comment]
> Oh

no problem - I have made the work done so far to be master Español.. I just renamed it to `Español (Colombia)`
will remove it, and only have `Español`

> P.s. there's no a on the end of 'Español' 😆

Strangely, I didn't add that. 
This is the current demo site:

image

will remove.

**Comment by adamdewey** [comment]
Perfect, thanks Mark! 

I blame that dodgy Spanglish translator we hired (😬)

**Comment by adamdewey** [comment]
Is there a way to also rename the sets in weblate? 

So these are swapped around in the UI?

image

**Comment by mark-prins** [comment]
The names in weblate should come right, once we merge the changes to `main` 🤞

**Comment by andreievg** [comment]
@mark-prins, since I couldn't test with:
> The Spanish language option has been renamed; you can test the override by adding something to the es-CO translation files, and checking: you'll see the es-CO item, all of the es translations and en translations for anything missed out of the first two.

I tested with `fr-DJ` and saw that app.json `outbound-shipment` was different between `fr` and `fr-DJ`, but `fr-DJ` seems to use `fr` `outbound-shipment` translation (also didn't see `fr-DJ` translations fetched in network api request)

Also as wondering how does the priority and hierarchy work ? How does it know to overall default to `en` and for `fr-DJ` to default to `fr` ?

**Comment by mark-prins** [comment]
> since I couldn't test with:

ah, thanks. have updated the initial comment to reflect the requested change to `es`

> I tested with fr-DJ and saw that app.json outbound-shipment was different between fr and fr-DJ, but fr-DJ seems to use fr outbound-shipment translation (also didn't see fr-DJ translations fetched in network api request)

The fr-DJ difference is just in `app.json` so yeah, it uses the same outbound-shipment json file for both.

> Also as wondering how does the priority and hierarchy work ? How does it know to overall default to en and for fr-DJ to default to fr ?

Magic? 🤷 

It's handled by the i18next package: the `en` is the default language ( set in the init of i18next ) so that will apply to all languages. We're using that as the base set as it will have all translations in it.

The `fr-DJ` -> `fr` is part of the package, as noted [in the docs](https://www.i18next.com/principles/fallback). Likely just taking the first part of the locale, I didn't actually check what the code is doing. Was just happy that the fallback works!

**Comment by andreievg** [comment]
> The fr-DJ difference is just in app.json so yeah, it uses the same outbound-shipment json file for both.

There is a difference in app.json, and it didn't matter what was set in fr-DJ (when I select that language, it still uses fr), so I couldn't validate that it actually works

**Comment by andreievg** [comment]
Hmm, here is a giff of me trying to get it working ¯\_(ツ)_/¯ (I tried incognito window, just in case something is cached)

Apr-18-2023 10-27-53

**Comment by mark-prins** [comment]
ah. sorry @andreievg - I reverted a change which I thought wasn't required.. and it is. 
have re-added the change now, in c1975c0ec

There's a secondary question about the wisdom of having currency tied to language.. we can address that later hopefully

**Review by andreievg — APPROVED** [review]
thanks Mark, re tested works as described

**Pull request merged**
