### PR TITLE
1863 Database error when viewing Programs tab after starting but not saving a new encounter

### LINKED ISSUE #1863: Database error when viewing Programs tab after starting but not saving a new encounter
Here's how to reproduce:

- Load a patient and add them to a Program (or pick someone already in a program but with no encounters)
- Start a new encounter, fill in the initial "Creation" modal, then go into the main encounter tab
- DON'T save the encounter, but exit out of it without saving
- Now go to the Programs tab for that patient -- you should get the following error, with nothing listed in the table:

Screenshot 2023-05-29 at 3 30 37 PM

### PR DESCRIPTION
**Pull request by roxy-dao**
Fixes #1863

# 👩🏻‍💻 What does this PR do? 
Added async to the program mutation... error seems to be gone for me 🤔 

# 🧪 How has/should this change been tested? 
- Enrol patient into program
- Start encounter but don't finish it
- Click out of the encounter creation modal
- Go back to program tab and things should load as expected

### CODE REVIEW

**Review by mark-prins — CHANGES_REQUESTED** [review]
Sorry! this is another one where I wander off and try to fix it myself. I believe that there's still an issue, because I can get the error even without hitting this code.

This is, as usual, just a suggestion. I think we need [something like this](https://github.com/openmsupply/open-msupply/compare/1863-Database-error-when-viewing-Programs-tab-after-starting-but-not-saving-a-new-encounter...1863-suggestion)

which is, set the URL query sort when changing tabs. The problem is that in the existing code, once the sort is set in the query, it is not updated by 'initialSort' and we do that when switching tabs. An alternative might be to unload the components - and I haven't explored that. I think the url query is set on component load, so that might work too.

I think that setting explicitly like this would be slightly faster though, as all the components are loaded and so switching tabs is faster.

**Comment by roxy-dao** [comment]
> Sorry! this is another one where I wander off and try to fix it myself. I believe that there's still an issue, because I can get the error even without hitting this code.
> 
> This is, as usual, just a suggestion. I think we need [something like this](https://github.com/openmsupply/open-msupply/compare/1863-Database-error-when-viewing-Programs-tab-after-starting-but-not-saving-a-new-encounter...1863-suggestion)
> 
> which is, set the URL query sort when changing tabs. The problem is that in the existing code, once the sort is set in the query, it is not updated by 'initialSort' and we do that when switching tabs. An alternative might be to unload the components - and I haven't explored that. I think the url query is set on component load, so that might work too.
> 
> I think that setting explicitly like this would be slightly faster though, as all the components are loaded and so switching tabs is faster.

I couldn't get the error anymore 🤔 Can you tell me the steps to reproduce with how it popped up for you?

**Comment by mark-prins** [comment]
> Can you tell me the steps to reproduce with how it popped up for you?

I have a patient which is already created, and is enrolled in a program. They have no encounters.

- View the patient
- Click on encounters tab
- Click on programs tab

That's all it takes for me. 

https://github.com/openmsupply/open-msupply/assets/9192912/f4ed2cfd-8a20-4d2d-a9a0-c1769350cb23

Now that I look at it - the encounters query ignores the sort in the URL query and will pass in in a key of `startDatetime` regardless of the URL query, which is why the issue is only on the Programs tab

**Comment by roxy-dao** [comment]
> Now that I look at it - the encounters query ignores the sort in the URL query and will pass in in a key of `startDatetime` regardless of the URL query, which is why the issue is only on the Programs tab

Makes sense to me to implement your changes so that the URL is correct when changing tabs (: 
Have also added initial sort to Encounters so it doesn't break on first load

**Review by mark-prins — APPROVED** [review]
👍 working nicely! thanks Roxy

**Pull request merged**
