### PR TITLE
1944 update sync translations

### LINKED ISSUE #1944: Add context table
From https://github.com/openmsupply/open-msupply/pull/903#issuecomment-1343827146

> context is now used in permissions and would be in reports, instead of just being a 'string' we can consider context table, could be permission_context, this would allow general report view to be generically filtered by permission context which can be used for other things (not programs) and if we want to show program <-> permission context relation we should be able to add a relation on program to that context

There has already been some work done to attach a context to various program tables.

- [x] Finalize design
- [x] Create context table and wire them up with other tables

Design:
- [x] Context table: has a primary ID column and a name/description column (the name column is only for debugging)
- [x] Tables like `programs`, `permission` or `document` refer to the context table through a `context_ID` column
- [x] `program_enrolment` and `encounter` tables refer to the `program` table and join the `context` table to get the `context_ID`

Others:
- [x] Document Registry: there is no real need for a parent anymore since we could find the parent by looking at the context  column
- [x] CapabilityTag can be removed because context are unique now, i.e. we can just read the full list of a user's allowed contexts
- [x] openmsupply/msupply#13357
- [x] When mSupply fields are changed, update sync
- [x] Make program::context_id non-optional and create context entries for existing program entries (in migration) + tests
- [x] Rename existing context references, e.g. in graphql, and update FE
- [x] Update schema repo (feature branch already created)
- [x] Rename document_registry.type to document_registry.category

### PR DESCRIPTION
**Pull request by clemens-msupply**
Fixes #1944

# 👩🏻‍💻 What does this PR do? 
Updates integration tests

# 🧪 How has/should this change been tested? 

- Setup central server from latest mSupply `develop` branch
- Run integration tests

The tests were a bit flaky in that there were constant problems with the hardware id not matching. I didn't manage to run all integration test though... any idea why? (document and document_registry run through though)

### CODE REVIEW

**Review by andreievg — APPROVED** [review]
Looks good, thanks.

**Comment by andreievg** [comment]
I was thinking about compatibility. I think we don't need to increment sync version, we could possibly re-integrate sync_buffer for related records on upgrade of omSupply (in case mSupply version was higher and we synced configurations)

**Comment by clemens-msupply** [comment]
> I was thinking about compatibility. I think we don't need to increment sync version, we could possibly re-integrate sync_buffer for related records on upgrade of omSupply (in case mSupply version was higher and we synced configurations)

Have a couple of questions about it but will ask you in the office later this week...

**Comment by andreievg** [comment]
> Have a couple of questions about it but will ask you in the office later this week... 
👍 
I've added to the list of things to talk about next week

**Pull request merged**
