### PR TITLE
Remove GROUP_MAX_WIDTH to fix some group control issues

### PR DESCRIPTION
**Pull request by clemens-msupply**
@CarlosNZ this seems to fix the current layout but you might have had something with it in mind?

Related to https://github.com/openmsupply/open-msupply/issues/424

### CODE REVIEW

**Comment by mark-prins** [comment]
@clemens-msupply can you let me know what the layout issues are? am trying to review and not sure what I'm looking for!

**Comment by clemens-msupply** [comment]
You had it in the slides this morning :) the programs enrolment JSONFroms layout was not probably aligned...

image

**Comment by mark-prins** [comment]
ah, ok. didn't notice 🙄 

in that case.. I suggest 8622cacce

Just updating the fixed width makes everything look a little lop-sided:


Screen Shot 2022-08-08 at 2 42 37 PM

changing the balance to 25% / 75% will make the form feel more centered:

Screen Shot 2022-08-08 at 3 01 54 PM

but does require some changes, more than just a comment allows!
Also - I removed the `flex={1}` as allowing the flex-grow when you want a fixed flex-basis could be problematic.

**Review by mark-prins — APPROVED** [review]
👍  that fixes it! though I also have committed a suggestion, which you may wish to revert before merging.. it is just a suggestion after all.

**Comment by clemens-msupply** [comment]
> but does require some changes, more than just a comment allows! Also - I removed the `flex={1}` as allowing the flex-grow when you want a fixed flex-basis could be problematic.

Thanks this looks better!

**Pull request merged**
