### PR TITLE
1737 Requisitions - Confirmation message on Finalisation

### LINKED ISSUE #1737: Requisitions - Confirmation message on Finalisation
Could possible be implemented for other invoices as well, maybe 🤔 

## Is your feature request related to a problem? Please describe 👀
Sometimes forget to create shipments for items to supply and press finalised instead. This is an easy mistake to make even when someone has been trained on omSupply.

## Describe the solution you'd like 🎁
Have a popup message to confirm if the user wants to finalise. Maybe the same message that mSupply shows? 
Screenshot 2023-05-11 at 9 10 40 AM 1

### Describe alternatives you've considered 💭
Just leave it as it is 🤷🏻

### PR DESCRIPTION
**Pull request by roxy-dao**
Fixes #1737

# 👩🏻‍💻 What does this PR do? 
Confirmation message suddenly started working again... but have added an extra message if the requisition hasn't been fully supplied to make it clearer to users...
Screenshot 2023-09-14 at 9 07 45 AM

# 🧪 How has/should this change been tested? 
- [ ] Go to requisition
- [ ] Don't supply total requested
- [ ] Try finalise
- [ ] Should see message pop up

### CODE REVIEW

**Comment by DhanyaHerath** [comment]
A request :) Could we rephrase this message to something like: 

`Not all items in this requisition have been supplied to the customer. 
If you finalise you will not be able to supply any more items to the customer from this requisition. Would you still like to continue? `

And if possible...make the `OK` button say `Finalise`?

**Review by mark-prins — APPROVED** [review]
👍  that's working nicely!

There's an additional request from @DhanyaHerath which I'm not seeing "And if possible...make the OK button say Finalise?"

I can still finalise a response requisition which has not had a shipment created, which feels like a similar problem - it does not appear to be handled in mSupply, so I'll assume that it's not a valid concern

**Comment by DhanyaHerath** [comment]
> I can still finalise a response requisition which has not had a shipment created, which feels like a similar problem - it does not appear to be handled in mSupply, so I'll assume that it's not a valid concern

@mark-prins shouldn't that get caught by this alert because it inherently means that not all items have been supplied?

**Comment by mark-prins** [comment]
no, you can supply without creating an invoice. The supply quantity is just an intention to supply and that's the value which is caught by this alert

**Comment by roxy-dao** [comment]
> no, you can supply without creating an invoice. The supply quantity is just an intention to supply and that's the value which is caught by this alert
I was told that was the value that was being caught in mSupply alert too 🤔

**Comment by mark-prins** [comment]
Well - try this:

- Log into store A
- Create an internal order for store B, set status to `Sent`
- Change to store B
- Open the requisition, try to finalise: **prompted**
- Set the `supply` quantity to be the `requested`
- try to finalise: **no prompt**

I can finalise even though I have not created an invoice, and I have a non zero value for `remaining`

image

the mSupply version has quantity values populated from the invoices created by the req. 
In mSupply this is:

```
  $ar_remaining{$i}:=$ar_requested{$i}-$ar_issued{$i}
```

and
```
  $r_not_supplied:=Sum($ar_remaining)+Sum($ar_to_be_supplied)
```

where `issued` comes from invoices created from the requisition.

What about using the `remainingQuantityToSupply` property of the requisition lines? that should be 0 to avoid the prompt I think.

**Pull request merged**
