### PR TITLE
Outbound Shipment add item modal Ux improvements

### LINKED ISSUE #1052: Discussion: the Add item window for outbound shipments is causing some confusion
Pauline and Damon found this very confusing during testing, as did Emily when she saw it later. 

I think a lot of the confusion comes from the fact that there's a mix of units used (units, and number of packs). I know this is a small UI issue, but if there is too much confusion it does add a lot of extra difficulty. 

image

Would appreciate any thoughts on this!

### PR DESCRIPTION
**Pull request by mark-prins**
Fixes #1052

# 👩🏻‍💻 What does this PR do? 
 
- Reorders the columns [as per the issue](https://github.com/openmsupply/open-msupply/issues/1052#issuecomment-1413060618), with the exception of the quantity input - I couldn't cope with that being mid-table, so pushed it out to the left hand edge
- Renamed the columns, also as [noted in the issue](https://github.com/openmsupply/open-msupply/issues/1052#issuecomment-1413060618) which makes them not fit very well
- Added the info icon to column headers which have a description, as [requested by @anisha-msupply ](https://github.com/openmsupply/open-msupply/issues/1052#issuecomment-1425026502) which also makes the column headers not fit very well
- bottom-aligned the column headers to make them look a little better
- add a button to manually **Allocate** the quantity, which was the decision from [our meeting](https://github.com/openmsupply/open-msupply/issues/1052#issuecomment-1423463855)
- Removed the onChange event which updated quantities between the various inputs
- Added a **Total** row which adds up the number of packs and number of units
- restyled the **Placeholder** row so that it looks like a row
- Fixed a few bugs with the pack size drop down
  - When opening a line in which the placeholder row is the only one with a quantity allocated, the option `Any` is now available and selected ( allows for auto-allocation to distribute to stock lines which have pack sizes other than 1 )
  - If there is only one pack size available, but every stock line is expired, then add in the `Any` option ( otherwise if click the allocate button, then it cannot auto allocate to a placeholder row, because the placeholder will have a different pack size )
- restrict the amount requested per line to the available quantity

# 🧪 How has/should this change been tested? 

The tests in `usePackSizeController.test.tsx` cover the pack size scenarios.
Other testing is manual:
- [ ] validate the columns are ordered as requested
- [ ] validate the columns have the right names 
- [ ] the columns show tooltips and info icons
- [ ] the **Allocate** button behaves 
- [ ] The inputs aren't auto-updating other inputs on changing
- [ ] the total row updates correctly
- [ ] when auto-allocating, the placeholder value is reduced to 0 if stock is available to fulfil the requested amount
- [ ] you cannot request more quantity on a line than is available

## 💌 Any notes for the reviewer?

The modal now looks like this on desktop:
Screenshot 2023-02-16 at 12 50 45 PM

and like this on mobile:
Screenshot 2023-02-16 at 12 53 53 PM

A closer look at the info tooltips:
Screenshot 2023-02-15 at 2 15 24 PM

## 📃 Documentation

- [ ] Screenshots will need updating
- [ ] The function of the **Allocate** button needs explaining
- [ ] Mention the use of placeholders and that the total row exists

### CODE REVIEW

**Comment by andreievg** [comment]
Just doing a quick test before review. What should be the behaviour for null expiry date ? Also seeing extra `s` if item doesn't have a unit `Issue 0 packs of 10 Unitss`

**Comment by mark-prins** [comment]
> Just doing a quick test before review. What should be the behaviour for null expiry date ? Also seeing extra `s` if item doesn't have a unit `Issue 0 packs of 10 Unitss`

a null expiry date is considered blank i.e. not expired. that stock line is available for selection / allocation. because we don't know if this is short expiry or not, we allocate stock lines with an expiry date first

Fixed the unitss in d8fc217218a5d5fdbc6f8254d3943cb33770166b

**Comment by DhanyaHerath** [comment]
I love the look of the  ⚡ Allocate ⚡ button Mark! Excited to see this happen, and to see what user reactions are like

**Comment by andreievg** [comment]
> a null expiry date is considered blank i.e. not expired. that stock line is available for selection / allocation. because we don't know if this is short expiry or not, we allocate stock lines with an expiry date first

@mark-prins I am just going up the list of PR, but remembered this comment. I originally wrote that question because I saw `null` treated like expired (just had one batch for an item with null expiry)

**Comment by andreievg** [comment]
@mark-prins 

> @mark-prins I am just going up the list of PR, but remembered this comment. I originally wrote that question because I saw null treated like expired (just had one batch for an item with null expiry)

I can't replicate

**Pull request merged**
