### PR TITLE
#109 Separate errors for Timeout and Unauthenticated

### LINKED ISSUE #109: Incorrect authentication error notification (f/e)
Just something I've noticed lately -- I keep getting the "Timed out" message even when it should be just a regular unauthenticated error.

If I restart the server and refresh the page, I get the following, even though you can see the server is returning "Unauthenticated":
Screen Shot 2022-06-09 at 11 17 16 AM

### PR DESCRIPTION
**Pull request by CarlosNZ**
Fix #109

### CODE REVIEW

**Comment by mark-prins** [comment]
I set the cookie timeout to a minute and waited..

image

And if on the dashboard, a query is made, which then throws an error. Only the permission denied message is shown and I'm not redirected to the login page, I can click ok and stay on the site but things behave strangely. Am looking into it now - there was another check for 'Unauthenticated' that needs to be changed

**Comment by mark-prins** [comment]
To get the timeout to work I've had to change `skipNoStoreRequests` in AuthContext to be:

```
  const skipNoStoreRequests = (documentNode?: DocumentNode) => {
    if (!documentNode) return false;

    if (documentNode.definitions.some(isAuthRequest)) return false;

    switch (LocalStorage.getItem('/auth/error')) {
      case AuthError.NoStoreAssigned:
      case AuthError.Unauthenticated:
      case AuthError.Timeout:
        return true;
      default:
        return false;
    }
  };
```

as well as setting the refresh timer to be greater than the cookie timeout. Otherwise the cookie is timed out but the refresh request is made after this and succeeds. Then the state becomes a little strange.

I've also changed line 44 in AuthenticationAlert to be

```
if (error === AuthError.Unauthenticated || error === AuthError.Timeout) {
```

so that the user is returned to where they were after a timeout.

**Comment by CarlosNZ** [comment]
> I set the cookie timeout to a minute and waited..

Oh, I did actually try that too -- guess I missed something. 

Anyway, thanks for looking into it. You'll push your update to this branch?

**Comment by mark-prins** [comment]
> You'll push your update to this branch?

I'm not sure that I've fixed it properly - when testing earlier the refresh token change was needed, but is not a long term solution. the refresh has to happen before the cookie times out.

I had dumped my changes, but I've put them back in and will commit those. Testing by deleting the cookie works ok - and shows the timeout error

**Comment by mark-prins** [comment]
It's still a bit funky - in that I get `Unauthenticated` when I've been sitting around for a bit.. so I've been previously logged in and it doesn't tell me I'm timed out.

I still like the distinction, so I think we should merge anyway. Have put in a small change to get the interval running on subsequent login attempts, which it wasn't previously ( interval is cleared after the first timeout ) and that's better - you get 'unauthenticated' and then up to a minute later that changes to 'timed out'.  We could reduce the time by making the interval check more frequent, but I think what we have is fine.

**Review by mark-prins — APPROVED** [review]
Let's go for it.. I've put in another minor change. If you think that's ok then merge away!

**Comment by CarlosNZ** [comment]
> Let's go for it.. I've put in another minor change. If you think that's ok then merge away!

Thanks Mark, yeah let's put this one through now, we can iron out the kinks as we go along :)

**Pull request merged**
