### PR TITLE
Update mui versions

### LINKED ISSUE #2043: Update mui packages
## Is your feature request related to a problem? Please describe 👀
Update the material packages
- `@mui/x-date-pickers` to v6.10.2
- `@mui/icons-material` to v5.14.1 (programs)
- `@mui/material` to v5.14.2 (common)

### PR DESCRIPTION
**Pull request by mark-prins**
Fixes #2043, #1842 

# 👩🏻‍💻 What does this PR do? 
 
Updates the mui versions. The changes required were just in date and time pickers

# 🧪 How has/should this change been tested? 

Have a look at the date and time pickers. These should look as they did, and should function correctly.
I've run through patient editing (incl. DoB), editing a program enrolment, adding and editing an encounter. Have looked at existing and new data. 
Ran unit tests.

## 📃 Documentation

_No user facing changes_

### CODE REVIEW

**Comment by andreievg** [comment]
@CarlosNZ can you please look at this PR (since you've mentioned you have some idea of how it should be done, or have experience with date picker for programs), thanks

**Comment by CarlosNZ** [comment]
> @CarlosNZ can you please look at this PR (since you've mentioned you have some idea of how it should be done, or have experience with date picker for programs), thanks

Sure, will do.

**Review by CarlosNZ — APPROVED** [review]
Cool, looks good thanks. Much easier to enter dates manually now.

I think we can actually get rid of the `internalValue` state within BaseDatePickerInput and DateTimePickerInput now, as it was only there as an intermediary to handle some inconsistent Date values that would cause the MUI component to crash (I think). Just quickly checking it seems to work fine without that now.

You can leave that for now though and I'll go through and check that thoroughly in a new issue if you want -- just let me know.

**Comment by roxy-dao** [comment]
The date component shows error but still lets the user save...

**Comment by mark-prins** [comment]
thanks for reviews!
I've taken out the internal value and checked the validation. Looking much neater - and the validation is working now for the date of birth, the encounter detail view, program enrolment and stocktake detail view.

**Comment by CarlosNZ** [comment]
> The date component shows error but still lets the user save...

I think it always did this, but it was even worse cos it didn't even show the error state if you entered it manually (it just prevented you from selecting an invalid date from the Picker).

We should probably make a new issue to solidify this, but it'll be a JSON Forms validation issue, not a Date Picker issue, I would think.

**Pull request merged**
