### PR TITLE
Filter out unallocated lines when making a duplicate in shipment tran…

### LINKED ISSUE #1347: Placeholders lines are received in omSupply as normal shipped lines
## What went wrong? 😲
 
In stock transfer, if the customer invoice in mSupply has placeholder lines, they are considered in omSupply as normal shipped lines.

In the example below, the supplier store has created a customer invoice for the lines requested. There was no stock on hand for one of the line so it stayed as placeholder line to be sent later.  

This is what is on the customer invoice of the supplier store
image

This is what you would see on the invoice. The place holder line is considered as not shipped.
image

 This is what you see on the inbound shipment
image

## Expected behaviour 🤔

Should probably be identified as not having been shipped in some way like colored in red and/or having the quantity set to 0 or something else

## How to Reproduce 🔨

Steps to reproduce the behaviour:

1. from omSupply create an internal order and have at least one item you know the supplier will not be to supply
2. From the supplier store fill the response requisition and create the customer invoice.
3. in the customer invoice provide the quantity requested except for the item you have no stock for. Keep the placeholder line
4. Confirm the invoice and click OK and Finalise when asked.
5. Go back and check in the omSupply your supplier invoice in Replenishment > inbound shipment. See error the line is not different for any other lines which makes you think that it will be delivered to you.

## Your environment 🌱
 - Version [e.g. 1.1.5 and 7.3.1 on Desktop]
 - Platform [e.g. tablet]

### PR DESCRIPTION
**Pull request by andreievg**
Fixes #1347 

This PR is based from MAIN, also there is another branch that is similar named (deleted) watch out

# 👩🏻‍💻 What does this PR do? 

Filter out unallocated lines before creating a transfer

# 🧪 How has/should this change been tested? 

As per issue

## 💌 Any notes for the reviewer?

I ran the test I added before and after the fex (it failed before the fix)

### CODE REVIEW

**Review by mark-prins — COMMENTED** [review]
When testing I get this:

image

which appear to be due to a FK violation

```
2023-03-21 12:41:57.191633 WARN service::sync::translation_and_integration - ForeignKeyViolation("\"insert or update on table \\\"invoice_line\\\" violates foreign key constraint \\\"invoice_line_stock_line_id_fkey\\\"\"") "0ED33A5959204BDEA8373BA5FB14908D" "trans_line"  service/src/sync/translation_and_integration.rs:125
2023-03-21 12:41:57.212009 WARN service::sync::translation_and_integration - ForeignKeyViolation("\"insert or update on table \\\"invoice_line\\\" violates foreign key constraint \\\"invoice_line_stock_line_id_fkey\\\"\"") "69C178883223495EB36CEA3AA058C8B1" "trans_line"  service/src/sync/translation_and_integration.rs:125
2023-03-21 12:41:57.232185 WARN service::sync::translation_and_integration - invalid type: null, expected struct LegacyTransLineRow at line 1 column 4 "86509E734CB949F08FA626C7DB564EDC" "trans_line"  service/src/sync/translation_and_integration.rs:85
2023-03-21 12:41:57.276600 INFO service::sync::synchroniser - Upsert Integration result: TranslationAndIntegrationResults({"requisition": TranslationAndIntegrationResult { integrated_count: 1, errors_count: 0 }, "transact": TranslationAndIntegrationResult { integrated_count: 2, errors_count: 0 }, "requisition_line": TranslationAndIntegrationResult { integrated_count: 2, errors_count: 0 }, "trans_line": TranslationAndIntegrationResult { integrated_count: 3, errors_count: 3 }})
```

Initial testing was using postgreSQL - have retried the scenario with sqlite and have the same issue.

existing problem perhaps? Currently unable to test the fix; given that this is a patch to main, I'd like to verify

**Comment by andreievg** [comment]
@mark-prins thanks! Ohh man, looks like we are getting transfer from mSupply (mSupply is creating the transfer : /, it shouldn't it should see that site is using V5, and should not create the transfer).

> existing problem perhaps? Currently unable to test the fix; given that this is a patch to main, I'd like to verify

I wonder what version of mSupply @alainsussol was using for this ¯\_(ツ)_/¯, I am pretty sure it was working before, as it was tests in the early days and I thought I hear Timor tester go through these scenariors.

@Chris-Petty before I jump and look at 4d code, do you think there was a change that could have caused this ?

Use case, create a site and two stores (one site on central one site on remote), sync remote, create customer invoice to remote site, sync remote site, see -1 invoice number and integration error for invoice line (since it was auto created and duplicate for some reason still has item_line_ID).

**Comment by Chris-Petty** [comment]
@andreievg not that I can think of. [transactTransferHandler is the method](https://github.com/sussol/msupply/blob/7bb36ea4e434af960109315dddfbcc9d91c05fb6/Project/Sources/Methods/transactTransferHandler.4dm) that determines whether or not to create a transfer on the central server, but regrettably only applied through the sync routes. You're right that if the store making the CI is active on the central server, it'll generate the transfer regardless of whether the store is on omSupply.

That said, often stores and sites get setup, used as customers, but aren't actually deployed/synced to a device yet. Likewise, stores can be moved from one site to another. That store may have been on a desktop remote site, then moved to omSupply. Currently we handle this partially regarding the `-1` serial numbers in [syncV5API_initialise](https://github.com/sussol/msupply/blob/b0f1d1388fa579596a8b86d869c2c2529e7b5320/Project/Sources/Methods/syncV5API_initialise.4dm). But that doesn't capture moving stores from desktop/mobile sites to omSupply sites actively in use.

So either omSupply needs to handle -1 invoice numbers and `item_line_ID`, or we can make the adjustments in 4D that ensure all is well all of the time. Preference? I'd rate the 4D changes "a day" including review and testing.

**Comment by andreievg** [comment]
@mark-prins I've tested and this looks fine when order from desktop is form a different site (store that is sending customer invoice is not active on central).

@Chris-Petty thanks, made an issue: https://github.com/openmsupply/open-msupply/issues/1396

**Comment by alainsussol** [comment]
@andreievg I am not sure what these symbols means 
image

but I have tested with with v7.2 and v7.3.  It didn't seem to happen to me but I was testing on a Sync mirror setting (East Timor) and I was sending request requisitions to an active supplier store on the primary and it was working. Following your comments I wanted to try again this morning but I had problems with my omSupply setup and now I get to the initialise screen but omSupply says it cannot initialise. I will try again a bit later...

**Review by mark-prins — APPROVED** [review]
👍 code looks fine. have been unable to test due to my sync ignorance ( supplier invoice isn't being created 🤷  ) 
Tests pass and it looks sensible to me.

**Comment by andreievg** [comment]
@alainsussol 

> @andreievg I am not sure what these symbols means

¯\_(ツ)_/¯ just mean shoulder shrug, like, i don't know, i am not sure.

**Comment by alainsussol** [comment]
@andreievg @mark-prins It happened to me too today for one outbound shipment to a mobile store where the supplier invoice was not created. However every other one I did on desktop and mobile afterwards were created normally. So maybe I didn't do the steps right between the response requisition and creating the shipment.

**Comment by Chris-Petty** [comment]
@alainsussol tangentially, when you create an outbound shipment from a requisition, is changing the customer store on the outbound shipment locked?

**Pull request merged**
