### PR TITLE
Introduce a NotFound std error and use for single stocktage queries

### PR DESCRIPTION
**Pull request by clemens-msupply**
In the last meeting we briefly mentioned a "simpler" way to return single entries (All errors are std errors). I created the draft PR to give an example how it would look like.

### CODE REVIEW

**Comment by andreievg** [comment]
I forgot, that certain things can be removed (it's not so with documents, as they cannot be removed), we might want to ask F/E team about this. If something is removed concurrently (i.e. user 1 sees list, user 2 deleted record, user 1 tries to access record), in that case, do we want a generic untranslated error shown to user ?

**Comment by clemens-msupply** [comment]
We could make it clear in the api by returning an `Result<Option<Node>>` if an entry could be removed. If it can't be removed we return `Result<Node>` + std error.

**Comment by andreievg** [comment]
> We could make it clear in the api by returning an Result<Option<Node>> if an entry could be removed. If it can't be removed we return Result<Node> + std error.

I haven't quite looked at f/e logic for this, it really depends on their existing patterns of error handling, if it's better or more consistent to match on specific error type vs checking optionals (now that I think about its, both options will quite likely happen in the same hook, so probably little difference).

**Comment by mark-prins** [comment]
I've tested with the f/e and the changes are fine - we do get an extra alert, but I think that one is fine.

While checking, I noticed that the stocktake modal requires two clicks to dismiss, strangely. Have put in a fix for that, into this branch.

Shall we go ahead with the changes then? This has been drafty for a while now..

**Comment by clemens-msupply** [comment]
Thanks @mark-prins ! Question was if this is easier/ same for the FE? From the BE side I think its easier to only return the Node + std errors for single query endpoints.

**Comment by mark-prins** [comment]
for the f/e it would be the same; we aren't checking specific error types on the return

**Comment by mark-prins** [comment]
Screen Shot 2022-06-29 at 11 51 57 AM

This is how the client shows the error now

**Comment by mark-prins** [comment]
> Shall we go ahead with the changes then? This has been drafty for a while now..

bump. can we merge?

**Comment by clemens-msupply** [comment]
I will close for now I think there is not strong need for it right now and would require quite a bit of refactoring...

**Pull request closed without merging**
