### PR TITLE
#895 Prevent tab switching from losing unsaved data.

### LINKED ISSUE #895: Programs tab navigates away from Details tab even when you tell it not to.
To reproduce:

- Start creating a new patient and fill in some details on the "Details" tab
- Click the "Programs" tab
- You will get an alert about losing unsaved changes if you navigate away
- Click "cancel"
- The app switches to the Programs tab anyway, and the unsaved data is lost forever 😢

### PR DESCRIPTION
**Pull request by CarlosNZ**
Closes #895.

Simple fix, and I actually prefer it this way anyway -- the "onChange" method for the tab switcher just updates the URL, and then the useEffect updates the current tab based on the url. 

This keeps the one-way information flow (as opposed to having to keep currentTab in sync with the url), and also allows the "beforeunload" listener to intercept the event and not update the URL if cancelled. (The event was already being detected, but didn't prevent tab switching as the "setCurrentTab" was being called directly rather than via URL change)

### CODE REVIEW

**Review by mark-prins — COMMENTED** [review]
The fix works nicely!

There's a follow-up issue though: if you do change tabs, and then change back to details you've got this showing:

Screenshot 2022-12-22 at 6 31 36 PM

I wonder if we should either warn people that this is the result of the action they are taking, or remove the tabs when creating a new patient, to avoid the problem? Or..?

I'm thinking to disable the tabs, and enable when the patient is created.

Another issue!

I click cancel down the bottom, click OK on the modal and then get this:

Screenshot 2022-12-22 at 6 34 42 PM

Clicking cancel on the second prompt gives you the blank patient view.

**Comment by CarlosNZ** [comment]
> I wonder if we should either warn people that this is the result of the action they are taking, or remove the tabs when creating a new patient, to avoid the problem? Or..?
> 
> I'm thinking to disable the tabs, and enable when the patient is created.

Yes, I agree, though I'll do that in a new issue -- #991 

> I click cancel down the bottom, click OK on the modal and then get this:

Okay, that should be included here. Will do.

**Comment by CarlosNZ** [comment]
> > I click cancel down the bottom, click OK on the modal and then get this:
> 
> Okay, that should be included here. Will do.

Okay @mark-prins, I've done this: a2473a5f8

I've just removed the "cancel confirmation" from the PatientView/Footer as its navigation was causing the event listener for "useConfirmOnLeaving" to fire (and that's baked into `useJsonForms` and can't easily be disabled). So now the cancel button just directly attempts a `navigate` (back 1) which causes just the native "alert" in `useConfirmOnLeaving` listener to fire when appropriate.

It'd be better to have the "nice" modal rather than the browser `alert`, but we can look at that another time (I suspect you already tried that and there's a reason that it's not straightforward).

**Comment by mark-prins** [comment]
> It'd be better to have the "nice" modal rather than the browser alert, but we can look at that another time (I suspect you already tried that and there's a reason that it's not straightforward).

Yep. totally - would be better to have a nice modal, and I have tried. It was possible with the previous version of react router, but that hasn't been brought into the new version (yet)

**Review by mark-prins — APPROVED** [review]
👍  LGTM!

**Pull request merged**
