### PR TITLE
1107 enforce item visibility by master list for store

### LINKED ISSUE #1107: Enforce item visibility by master list for store
Currently visibility is by master list available on site, rather then for store, can do something like this inner query: https://github.com/openmsupply/open-msupply/compare/Example-item-visibility

@DhanyaHerath @mark-prins adding milestone to this as I think it is hard requirement for Android Stabilisation and @roxy-dao was doing something with item performance that may require this change (as in would need to be in this sprint)

### PR DESCRIPTION
**Pull request by roxy-dao**
Closes #1107 

- Delete item_is_visible view
- Filter items by master list and store
- Update related functions to filter items by is_visible
- Update frontend api call to only fetch items that are visible

### CODE REVIEW

**Review by mark-prins — APPROVED** [review]
👍 is working nicely & code changes look good to me!
Perhaps also add a migration script to delete the view for existing databases?

Side note: the total items count on the dashboard is incorrect - I have more than 100 items and it is only showing 100 as the total count

**Comment by roxy-dao** [comment]
> Side note: the total items count on the dashboard is incorrect - I have more than 100 items and it is only showing 100 as the total count

🤔 Just noticed that... tested on develop and still get the same numbers. Can investigate it here or merge this first and move it into a different issue?

**Comment by mark-prins** [comment]
I tested on develop too! 😆 
I think merge this one. I'll track down the PR in which I changed the total items query and see what's happened - I'm sure it was showing correctly previously 🤷

**Comment by roxy-dao** [comment]
> 813d05b

Guess I'll just do it here 🏃🏻

**Pull request merged**
