### PR TITLE
add linter option

### LINKED ISSUE #2427: Console.log lint
## Is your feature request related to a problem? Please describe 👀
A speculative issue - am wondering about adding the `no-console` lint option to catch `console.log` when committing. 

## Describe the solution you'd like 🎁
Allow `console.info` `console.error` and `console.warn` and change all of the test console calls to be info
Enable the hook option

### Describe alternatives you've considered 💭
I thought this might remove a minor PR feedback task

### PR DESCRIPTION
**Pull request by mark-prins**
Fixes #2427

# 👩🏻‍💻 What does this PR do? 
 
Adds the `no-console` lint option and updates code 

# 🧪 How has/should this change been tested? 

Try to commit a change which has 'console.log' in it

### CODE REVIEW

**Review by clemens-msupply — APPROVED** [review]
Thanks the pre commit hook didn't trigger though. Any idea why?

**Comment by mark-prins** [comment]
> Thanks the pre commit hook didn't trigger though. Any idea why?

Uh, It triggered for me 🤷 
The change was to the linter config, I don't see how that would affect the hook triggering.  🤔 
I just added a console.log to a file, staged it and tried to commit

**Comment by clemens-msupply** [comment]
> > Thanks the pre commit hook didn't trigger though. Any idea why?
> 
> Uh, It triggered for me 🤷 The change was to the linter config, I don't see how that would affect the hook triggering. 🤔 I just added a console.log to a file, staged it and tried to commit

Sorry, the commit hook ran but it didn't pick up the console.log. It complains in VSCode (eslint) though.

**Comment by mark-prins** [comment]
Strange - the commit hook picked it up for me.. let's merge and see if it helps anyone. easy enough to roll out, and I like having the linter in vscode anyway 🙏

**Pull request merged**
