### PR TITLE
74 document fixes

### PR DESCRIPTION
**Pull request by clemens-msupply**
Fixes some of the tasks in https://github.com/openmsupply/open-msupply/issues/74

### CODE REVIEW

**Review by mark-prins — APPROVED** [review]
👍 

I have nothing particularly helpful to add. It works for me.. like the use of the service_provider, that's very neat.

**Comment by andreievg** [comment]
I was wondering about the canonical json changes, there is no description about it in the PR, but i see some changes (and the checkpoint it checked of fin the issue)

(this might not be needed btw, if we agree on option 3 of sync and documents for now)

also this fails for me `cargo clean && cargo test --features postgres`

**Comment by clemens-msupply** [comment]
> I was wondering about the canonical json changes, there is no description about it in the PR, but i see some changes (and the checkpoint it checked of fin the issue)
> 
> (this might not be needed btw, if we agree on option 3 of sync and documents for now)
> 
> also this fails for me `cargo clean && cargo test --features postgres`

yes thanks know about the failing test but haven't looked into it yet...

The existing serde behaviour is already what we want so the current implementation just uses default serde. Main part of the file is a test to ensure that serde behaves correctly / doesn't change...

**Comment by andreievg** [comment]
@clemens-msupply I dont' understand, why have ConicalJsonValue at all ?
this test passes:
```rust
#[test]
    fn test_canonical_json() {
        let base = json!({
            "A": "string",
            "B": 1.23456789 as f32,
            "C": true,
            "D": 5 as i32,
            "E": [1 as i32, 2 as i32, 3 as i32],
            "F": {
                "AA": "str",
                "BB": 1.23 as f32,
            }
        });
        let base2 = json!({
            "C": true,
            "A": "string",
            "D": 5 as i32,
            "E": [1 as i32, 2 as i32, 3 as i32],
            "F": {
                "BB": 1.23 as f32,
                "AA": "str",
            },
            "B": 1.23456789 as f32,
        });

        assert_eq!(base.to_string(), base2.to_string());
    }

```

**Comment by clemens-msupply** [comment]
You see where it is used. Would also help if default behavior would (I guess it wouldn't though)

**Comment by andreievg** [comment]
> To have a reference implementation

I still don't understand, if tests pass on serde.to_string() implementation, why do we need a reference implementation ? (as long as we have the test and it passes)

**Comment by clemens-msupply** [comment]
Because, for example, there could be an error in the manual sorted one or serde suddenly does a wrong sorts. I luckily had the ref impl so why not use it? otherwise it would do with a manual stringified version (think I am doing it in some test).

**Comment by andreievg** [comment]
>  or serde suddenly does a wrong sorts

How would it suddenly do it differently ? (this would mean serde would break backwards compatibility). And we can have the above test to make sure backwards compatibility is maintained. 

Less code is always better imo, especially if that code is already implemented in widely used and supported library (that specialises in serialisation)

**Pull request merged**
