### PR TITLE
#2107 Invalid date format

### LINKED ISSUE #2107: Invalid date format
## What went wrong? 😲
 
Noticed when testing #2066 
When you add a new encounter the date format is different to the rest of the site which is using `DD/MM/YYYY` - for encounters, you can enter the following as a valid date:

Screenshot 2023-08-18 at 9 22 00 AM

I would also like to have the method implemented which was raised in [this comment](https://github.com/openmsupply/open-msupply/pull/2066#discussion_r1292858650) - to expand out this usage:

```
t(`error.date_${validationError}` as LocaleKey, {
  defaultValue: validationError,
})
```

into the exhaustive and more typesafe version:

```
const formattedDateError = (t: TypedTFunction<LocaleKey>, error: string) => {
  if (!error) return null;

  switch (error) {
    case 'date_invalidDate':
      return t('error.date_invalidDate');
    case 'date_minDate':
      return t('error.date_minDate');
    case 'date_maxDate':
      return t('error.date_maxDate');
    case 'date_disablePast':
      return t('error.date_disablePast');
    case 'date_disableFuture':
      return t('error.date_disableFuture');
    default:
      return error;
  }
};
```

## How to Reproduce 🔨

Steps to reproduce the behaviour:

## Your environment 🌱

 - Version: 
 - Platform:
   - [ ] android (tablet)
   - [ ] browser (extra points if you tell us which one)
   - [ ] desktop (windows)
   - [ ] desktop (macOS)
   - [ ] server (windows)

### PR DESCRIPTION
**Pull request by CarlosNZ**
Quick fix for #2107

# 👩🏻‍💻 What does this PR do? 
 

- Change the "DateTime" JsonForms component to use `DateTimePicker` rather than `BaseDateTimePicker` -- same thing, but passes a default format through to `BaseDateTimePicker`
- add switch/case for "getFormattedDateError" function (and move outside component)

# 🧪 How has/should this change been tested? 

Confirm that date format is correct for enrolment date input

### CODE REVIEW

**Comment by roxy-dao** [comment]
Currently can't do stocktake if the stock line has a date inputted 😢

**Comment by CarlosNZ** [comment]
> Currently can't do stocktake if the stock line has a date inputted 😢

Good catch. Looks like the Stock line was passing down the date as an ISO string. Have added a small tweak to make sure the "value" prop for the date picker is not a string, and convert it to a Date if it is. 91c5224af

Seems to work for this case and can't see any negative effects.

**Comment by roxy-dao** [comment]
Thanks Carl~

One more thing... the validation error on the Encounters page is always returning true... so can't save the Encounter if the clinician changes the date of the encounter 🙏🏻

**Comment by clemens-msupply** [comment]
> One more thing... the validation error on the Encounters page is always returning true... so can't save the Encounter if the clinician changes the date of the encounter 🙏🏻

Good catch! otherwise looks good to me

**Review by roxy-dao — APPROVED** [review]
Oh~ Seems to be working now! 
LGTM, thanks Carl~

**Pull request merged**
