### PR TITLE
Use same margins and gaps for JsonForms components

### PR DESCRIPTION
**Pull request by clemens-msupply**
Couldn't stand the misalignment anymore so at least fixed some issues...

@mark-prins could you please check my change to the common InputWithLabelRow?

### CODE REVIEW

**Comment by clemens-msupply** [comment]
We might want to put this layout config in one place at some point so that it will be easier to tweak it or even to configure it...

**Comment by clemens-msupply** [comment]
> > We might want to put this layout config in one place at some point so that it will be easier to tweak it or even to configure it...
> 
> Can you put it in `styleConstants.ts`?

I leave this for another time since I am busy with other things right now but yes that would be good!

**Review by mark-prins — APPROVED** [review]
👍 agree with Carl re the shifting to style constants, the changes themselves look good thanks

**Comment by clemens-msupply** [comment]
> +1 agree with Carl re the shifting to style constants, the changes themselves look good thanks

Yes lets do this in the next iteration! I don't want to get side track more just now.

**Pull request merged**
