### PR TITLE
1537 program event fixes

### LINKED ISSUE #1537: Fix program events when basetime changes
To reproduce:
- Create an HIV Care encounter and trigger an "Early LTFU"
- Modify the startDatetime of the encounter so that the programStatus should change to "LTFU"

This will not work because the program events for the old startDatetime are not cleared properly.

### PR DESCRIPTION
**Pull request by clemens-msupply**
Fixes #1537

To test:

- [ ] Create an HIV Care encounter and trigger an "Early LTFU"
- [ ] Modify the startDatetime of the encounter so that the programStatus should change to "LTFU"
- [ ] Program status should update correctly

### CODE REVIEW

**Comment by mark-prins** [comment]
I'm not sure how to test! I've created an encounter and the status is 'missed'
How do I trigger an "Early LTFU"?
I've added someone to the program, created an encounter and the program status is 'active'. Then changed the encounter time and it is still 'active'.. is that right?

**Comment by clemens-msupply** [comment]
The Missed/Early LTFU/ LTFU statuses scheduled by dispensing some pills in the ARV Medication section. This will set an "End of Supply" date.

The statuses are:
`Missed`: 0 days after the End of Supply date
`Early LTFU`: 28 days after the End of Supply date
`LTFU`: 90 days after the End of Supply date

The statues should show in the Program list view

**Comment by roxy-dao** [comment]
I can see the status in my DB, but can't see them displayed in the `Additional Info` column under Programs 🤔

**Review by roxy-dao — APPROVED** [review]
Thanks Clemens~

**Pull request merged**
