### PR TITLE
#1308 add is active to name store join

### LINKED ISSUE #1308: Add is_active to name_store_join
## Is your feature request related to a problem? Please describe 👀
Having name store join tables push to central is causing data discrepancies... because records which are inactive are deleted during sync

## Describe the solution you'd like 🎁
Add is_active to name_store_join table and don't delete db entries on sync

### Additional context 💌
Pushing name store joins to central is done in programs...

### PR DESCRIPTION
**Pull request by roxy-dao**
Fixes #1308 

# 👩🏻‍💻 What does this PR do? 
- Adds an is_active to name store join table
- Change is_visible filter to is_active

# 🧪 How has/should this change been tested? 
- Run tests

## 💌 Any notes for the reviewer?
- Programs will need to be updated from develop after this is merged and `patient_updated` will need updating

## 📃 Documentation

_No user facing changes_

or

- [ ] Functional change 1
- [ ] Functional change 2

### CODE REVIEW

**Review by mark-prins — COMMENTED** [review]
changes look fine - though I prefer `is_visible` and deleting the `name_store_join` records.
I'm just curious why this is necessary, and whether programs could just be changed, so that it doesn't push when it shouldn't.

**Comment by roxy-dao** [comment]
> changes look fine - though I prefer `is_visible` and deleting the `name_store_join` records. I'm just curious why this is necessary, and whether programs could just be changed, so that it doesn't push when it shouldn't.

- I can rename it to is_visible if that's what you prefer.
- The `delete` trigger on `name_store_join` doesn't seem to recognise the deletions from `pull_upsert` and even if it did, the next time the sites sync, it would delete `name_store_join` in central which is not ideal.

**Comment by mark-prins** [comment]
ah right. In that case I think we just go for it, and introduce the `is_active` flag - though @andreievg might have thoughts?

**Comment by roxy-dao** [comment]
> ah right. In that case I think we just go for it, and introduce the `is_active` flag - though @andreievg might have thoughts?

Just realised #1293 this issue probably fixes that anyways... Alright with you to close this? 🤔

**Comment by roxy-dao** [comment]
Though I think the circular issue might fix this too....

**Pull request closed without merging**
