### PR TITLE
Combined server+desktop installer

### LINKED ISSUE #1542: Combine client and remote server installer
## Is your feature request related to a problem? Please describe 👀

Create an installer which combines the server and desktop installers. Essentially the single user mSupply desktop install.

## Describe the solution you'd like 🎁
The installer will
- [ ] install the sqlite version of the server
- [ ] create a service
- [ ] start the service
- [ ] install the desktop version
- [ ] create a start menu shortcut for the desktop version
- [ ] Add the new installer to the jenkins build config

### Describe alternatives you've considered 💭
You can install the server and desktop separately. This is nicer though.

### Moneyworks Jobcode 🧰

DJUNCUST

### PR DESCRIPTION
**Pull request by mark-prins**
Fixes #1542

# 👩🏻‍💻 What does this PR do? 
 
This will create the sqlite service, install and start it, copy the desktop files, and create a shortcut on the user's desktop to the electron version.

Upgrading is just like the current installers.
Uninstall should also work as per the current installers.

# 🧪 How has/should this change been tested? 

Build - manually or using jenkins, by adding a `v...` tag to the branch.

## 📃 Documentation

- [ ] Need to update the install info

### CODE REVIEW

**Comment by clemens-msupply** [comment]
I get this error:

image

And from the event viewer it seems like there is no local.yaml:

image

**Comment by clemens-msupply** [comment]
Is this a Postgres/Sqlite only version? I didn't have the choice to select the DB type...

**Comment by mark-prins** [comment]
> Is this a Postgres/Sqlite only version? I didn't have the choice to select the DB type...

Only sqlite. I decided that the all-in-one version should only be sqlite and not mess around with installing postgres as well 🤷

**Comment by mark-prins** [comment]
> I get this error:

Yeah, me too. That's a problem in the electron build in develop. I'm not getting it in the dependency upgrade PR (#1616) I was going to fix it there.. but don't get it now. Maybe the update has resolved?

> And from the event viewer it seems like there is no local.yaml:

I didn't get that - and I have a local.yaml on my laptop. This was a fresh install though - and it would behave differently if you already have the server installed on the machine

**Comment by mark-prins** [comment]
Have reworked this a little
- check for server or desktop install prior to starting, and prevent if they are installed
- Fix a problem in local config
- Fix uninstall
- Change the registry key used for standalone to be specific

**Review by clemens-msupply — APPROVED** [review]
This is working for me now, thank you! (Apart from the error msg which is handled in another PR)

**Pull request merged**
