### PR TITLE
Upgrade dependencies

### LINKED ISSUE #1442: Dependency update f/e
## Is your feature request related to a problem? Please describe 👀

The ongoing saga of deps. The upgrade has just finished and the next round are ready to be upgraded. 
I'd like to have this as a more regular task to constrain the scope of the job. Hopefully we'll only have one major issue per upgrade if we keep on top of it.

## Describe the solution you'd like 🎁

# Major
| Package | Current | Wanted | Latest | Package Type | URL | CHANGELOG |
|---|---|---|---|---|---|---|
| @mui/x-date-pickers | 5.0.20 | 5.0.20 | 6.0.3 | openmsupply-client | dependencies | https://mui.com/x/react-date-pickers/ |  |

# Minor
| Package | Current | Wanted | Latest | Package Type | URL | CHANGELOG |
|---|---|---|---|---|---|---|
| @electron-forge/cli | 6.0.5 | 6.1.0 | 6.1.0 | @openmsupply-client/electron | devDependencies | https://github.com/electron/forge#readme |  |
| @electron-forge/maker-deb | 6.0.5 | 6.1.0 | 6.1.0 | @openmsupply-client/electron | devDependencies | https://github.com/electron/forge#readme |  |
| @electron-forge/maker-rpm | 6.0.5 | 6.1.0 | 6.1.0 | @openmsupply-client/electron | devDependencies | https://github.com/electron/forge#readme |  |
| @electron-forge/maker-squirrel | 6.0.5 | 6.1.0 | 6.1.0 | @openmsupply-client/electron | devDependencies | https://github.com/electron/forge#readme |  |
| @electron-forge/maker-zip | 6.0.5 | 6.1.0 | 6.1.0 | @openmsupply-client/electron | devDependencies | https://github.com/electron/forge#readme |  |
| @electron-forge/plugin-webpack | 6.0.5 | 6.1.0 | 6.1.0 | @openmsupply-client/electron | devDependencies | https://github.com/electron/forge#readme |  |
| @testing-library/dom | 9.0.1 | 9.2.0 | 9.2.0 | openmsupply-client | devDependencies | https://github.com/testing-library/dom-testing-library#readme |  |
| @typescript-eslint/eslint-plugin | 5.55.0 | 5.57.0 | 5.57.0 | openmsupply-client | devDependencies | https://github.com/typescript-eslint/typescript-eslint#readme |  |
| @typescript-eslint/eslint-plugin | 5.55.0 | 5.57.0 | 5.57.0 | @openmsupply-client/electron | devDependencies | https://github.com/typescript-eslint/typescript-eslint#readme |  |
| @typescript-eslint/parser | 5.55.0 | 5.57.0 | 5.57.0 | openmsupply-client | devDependencies | https://github.com/typescript-eslint/typescript-eslint#readme |  |
| @typescript-eslint/parser | 5.55.0 | 5.57.0 | 5.57.0 | @openmsupply-client/electron | devDependencies | https://github.com/typescript-eslint/typescript-eslint#readme |  |
| electron | 23.1.4 | 23.2.0 | 23.2.0 | @openmsupply-client/electron | devDependencies | https://github.com/electron/electron#readme |  |
| eslint | 8.36.0 | 8.37.0 | 8.37.0 | openmsupply-client | devDependencies | https://eslint.org |  |
| eslint | 8.36.0 | 8.37.0 | 8.37.0 | @openmsupply-client/electron | devDependencies | https://eslint.org |  |
| lerna | 6.5.1 | 6.6.1 | 6.6.1 | openmsupply-client | dependencies | https://lerna.js.org |  |
| msw | 1.1.0 | 1.1.0 | 1.2.1 | openmsupply-client | dependencies | https://mswjs.io |  |
| webpack-dev-server | 4.12.0 | 4.13.1 | 4.13.1 | @openmsupply-client/host | devDependencies | https://github.com/webpack/webpack-dev-server#readme |  |

# Patch
| Package | Current | Wanted | Latest | Package Type | URL | CHANGELOG |
|---|---|---|---|---|---|---|
| @graphql-codegen/typescript-graphql-request | 4.5.8 | 4.5.9 | 4.5.9 | openmsupply-client | devDependencies | https://github.com/dotansimha/graphql-code-generator-community#readme |  |
| @mui/material | 5.11.13 | 5.11.15 | 5.11.15 | @openmsupply-client/common | dependencies | https://mui.com/material-ui/getting-started/overview/ |  |
| @swc/core | 1.3.40 | 1.3.42 | 1.3.42 | openmsupply-client | devDependencies | https://swc.rs |  |
| @types/lodash | 4.14.191 | 4.14.192 | 4.14.192 | openmsupply-client | devDependencies | https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/lodash |  |
| @types/node | 18.15.3 | 18.15.11 | 18.15.11 | openmsupply-client | devDependencies | https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/node |  |
| @types/react | 18.0.28 | 18.0.31 | 18.0.31 | openmsupply-client | devDependencies | https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react |  |
| i18next | 22.4.11 | 22.4.13 | 22.4.13 | @openmsupply-client/common | dependencies | https://www.i18next.com |  |
| papaparse | 5.4.0 | 5.4.1 | 5.4.1 | openmsupply-client | dependencies | http://papaparse.com |  |
| prettier | 2.8.6 | 2.8.7 | 2.8.7 | openmsupply-client | devDependencies | https://prettier.io |  |
| webpack | 5.76.2 | 5.76.3 | 5.76.3 | openmsupply-client | devDependencies | https://github.com/webpack/webpack |  |
| webpack | 5.76.2 | 5.76.3 | 5.76.3 | @openmsupply-client/host | devDependencies | https://github.com/webpack/webpack |  |

### PR DESCRIPTION
**Pull request by mark-prins**
Fixes #1442 

# 👩🏻‍💻 What does this PR do? 
 
Dependency upgrades!

There's a bump in particular for storybook and electron, this PR has electron building - currently an issue in develop. 

# 🧪 How has/should this change been tested? 

- Storybook runs 
- and builds 
- electron runs 
- and builds
- jest is running
- site runs
- and builds
- android builds

The testing is really just running a `yarn install` and trying the various things. 

## 📃 Documentation

_No user facing changes_

### CODE REVIEW

**Comment by clemens-msupply** [comment]
Some tests are failing like:

````
● currency formatting - fr › formats a string with up to the precision number of decimal places, dropping decimal places where needed

    expect(received).toBe(expected) // Object.is equality

    Expected: "1,11 XOF"
    Received: "1,11 €"

      48 |     });
      49 |     const f1 = result.current.c(1.11111111111).format();
    > 50 |     expect(f1).toBe('1,11 XOF');
         |                ^
      51 |   });
      52 |   it('formats a string with up to the precision number of decimal places, dropping decimal places where needed even with large numbers', () => {
      53 |     const { result } = renderHookWithProvider(useCurrency, {

      at Object.toBe (packages/common/src/intl/currency/currency.test.tsx:50:16)
```

**Comment by mark-prins** [comment]
> Some tests are failing like:

Unrelated.. but also strange, as I ran all tests without a hitch. clearly didn't run them correctly.. the currency symbol was changed to euro some time ago!

Might as well fix in this branch - thanks!

**Comment by mark-prins** [comment]
Thanks @clemens-msupply have fixed the f/e tests in 7a02a25ab

**Review by clemens-msupply — APPROVED** [review]
Thanks, looks good! It builds all fine except of the electron Linux build (see child PR).

**Pull request merged**
