### PR TITLE
Add vaccine icon

### LINKED ISSUE #2108: make the "Covid 19 Vaccination History" programme an encounter type of the HIV Care & Treatment programme
Since recording C19 vaccination data is only meant for HIV patients, there is no need to have a separate program for Covid 19. In order not to have too many programs, we could add a new encounter type as part of the HIV Care & Treatment programme. 

- [x] Change section's logo to a vaccine logo ? Example: 

Screenshot 2023-08-18 at 11 42 43 AM

### Section 1: `COVID-19 Vaccination Services`

- [x] `Visit Date`: already captured in the encounter's headers
- [x] `Was client offered COVID-19 Vaccination ?`: check/tick box (true or false)
- [x] `Has client declined COVID-19 Vaccination ?`: check/tick box (true or false)
- [x] `If declined, reason given:`: free text

### Section 2: `COVID-19 Vaccination Event`

Note: this section should only be displayed if `Was client offered COVID-19 Vaccination ?` = `Yes`

- [x] `Vaccination Date`: date picker
- [x] `Manufacturer`: dropdown menu (Moderna, Pfizer, Astra-Zeneca, Sinovac, Johnson & Johnson, Other
- [x] `Comments`

## Moneyworks Jobcode 🧰

PG23THRFD

### PR DESCRIPTION
**Pull request by clemens-msupply**
Fixes #2108 

Adds a vaccine icon. This icon is used in the covid19 encounter (HIV care program).

image

For testing use the latest config from the schema repo and create a covid 19 encounter.

### CODE REVIEW

**Comment by roxy-dao** [comment]
Can you change the pregnancy icon as well while you're at it? 👀

**Comment by mark-prins** [comment]
Is the `injection` icon not good enough?

image

**Comment by mark-prins** [comment]
> Can you change the pregnancy icon as well while you're at it? 👀

oh! the `condom` has been used for a pregnancy section - I hadn't noticed that.

**Comment by clemens-msupply** [comment]
> Is the `injection` icon not good enough?
> image

Yes would be fine with that one.

**Pull request closed without merging**
