### PR TITLE
Postgres compilation

### LINKED ISSUE #114: Unable to compile with postgres feature
If you try to compile the programs feature branch with `--features postgres` you get

```
Compiling repository v0.1.0 (/Users/m2/GitHub/open-msupply/server/repository)
error[E0433]: failed to resolve: use of undeclared crate or module `document_head_dsl`
   --> repository/src/db_diesel/document.rs:153:29
    |
153 |         diesel::insert_into(document_head_dsl::document_head)
    |                             ^^^^^^^^^^^^^^^^^ use of undeclared crate or module `document_head_dsl`
    |
help: there is a crate or module with a similar name
    |
153 |         diesel::insert_into(document_head::document_head)
    |                             ~~~~~~~~~~~~~

error[E0433]: failed to resolve: use of undeclared crate or module `document_head_dsl`
   --> repository/src/db_diesel/document.rs:155:26
    |
155 |             .on_conflict(document_head_dsl::id)
    |                          ^^^^^^^^^^^^^^^^^ use of undeclared crate or module `document_head_dsl`
    |
help: there is a crate or module with a similar name
    |
155 |             .on_conflict(document_head::id)
    |                          ~~~~~~~~~~~~~

error[E0433]: failed to resolve: use of undeclared crate or module `json_schema_dsl`
  --> repository/src/db_diesel/json_schema.rs:65:29
   |
65 |         diesel::insert_into(json_schema_dsl::json_schema)
   |                             ^^^^^^^^^^^^^^^ use of undeclared crate or module `json_schema_dsl`
   |
help: there is a crate or module with a similar name
   |
65 |         diesel::insert_into(json_schema::json_schema)
   |                             ~~~~~~~~~~~

error[E0433]: failed to resolve: use of undeclared crate or module `json_schema_dsl`
  --> repository/src/db_diesel/json_schema.rs:67:26
   |
67 |             .on_conflict(json_schema_dsl::id)
   |                          ^^^^^^^^^^^^^^^ use of undeclared crate or module `json_schema_dsl`
   |
help: there is a crate or module with a similar name
   |
67 |             .on_conflict(json_schema::id)
   |                          ~~~~~~~~~~~

For more information about this error, try `rustc --explain E0433`.
error: could not compile `repository` due to 4 previous errors
```

### PR DESCRIPTION
**Pull request by mark-prins**
Fixes #114 

Just updated the types 😉

### CODE REVIEW

**Comment by andreievg** [comment]
> I wonder why the bundle size diff thing triggered:

Ohh it's because it's comparing to main

**Review by clemens-msupply — APPROVED** [review]
Thanks have a fix for this as well in my current branch but please go ahead!

**Review by andreievg — APPROVED** [review]

**Comment by mark-prins** [comment]
thanks @andreievg - have updated the tests.
Still have an issue with the pg tests, but at least it is sorry about it: 

```
     Running unittests (target/debug/deps/graphql_general-159bc836af8a8528)
...
     FATAL:  sorry, too many clients already
```

and it's not related to this PR.. so 🤷

**Comment by andreievg** [comment]
> sorry, too many clients already

@mark-prins I think it's max_connection in postgresql.conf (i think it should be minimum 100)

**Pull request merged**
