### PR TITLE
1398 update location from stock view 

### LINKED ISSUE #1398: Update location from stock view
## Is your feature request related to a problem? Please describe 👀

In mSupply can update location from stock view, but in omSupply this is missing

## Describe the solution you'd like 🎁

Choose and update location from stock view

### Additional context 💌

Screenshot 2023-03-22 at 9 53 48 AM

### Moneyworks Jobcode 🧰

Not sure, maybe as part of OMSTIMDEV work

### PR DESCRIPTION
**Pull request by roxy-dao**
Fixes #1398 

# 👩🏻‍💻 What does this PR do? 
Adds location to stock line
Screenshot 2023-04-20 at 12 22 46 PM

# 🧪 How has/should this change been tested? 
- Have locations at current store
- Edit stock line location

## 📃 Documentation

_No user facing changes_

or

- [ ] Functional change 1
- [ ] Functional change 2

### CODE REVIEW

**Review by CarlosNZ — APPROVED** [review]
LTGM! Thanks :)

**Comment by mark-prins** [comment]
Don't we need tracking for location movements? This is particularly for temperature dependent items, to track breaches. I thought that it was needed for all items though? @andreievg.. would you know?

You'd need to add entries to the `location_movement` table to capture the changes.

**Comment by roxy-dao** [comment]
> Don't we need tracking for location movements? This is particularly for temperature dependent items, to track breaches. I thought that it was needed for all items though? @andreievg.. would you know?
> 
> You'd need to add entries to the `location_movement` table to capture the changes.

https://github.com/openmsupply/open-msupply/issues/694#issuecomment-1482220718 Oh.. I will add it now, didn't see the extra info in the other issue

**Comment by mark-prins** [comment]
cool - thanks. was thinking this morning that we should go ahead and log the movement. just in case. was going to open a new issue 😄 
Made me think again about archiving data - that's a future problem!

**Comment by mark-prins** [comment]
> location_movement is already being updated (:

Oh?! sweet. thanks for checking

**Pull request merged**
