### PR TITLE
Remove program init data

### LINKED ISSUE #1276: Remove init code from the remote server
Remove `service/src/sync/init_programs_data.rs` and related schema and *.json files. Make sure all data is put onto the central server db file.

- [x] remove init_program_data
- [x] in `service/src/login.rs` remove `insert_programs_permissions`

### PR DESCRIPTION
**Pull request by clemens-msupply**
Fixes #1276 

All schemas from this repo are moved to the schema repository. Before merging this PR needs to update the schema repo first with the latest version of the schema files from this repo.
# Testing

This PR is quite straight forward but requires some more testing for the alternative workflow to setup a dev version of the remote server that has all document registry entries and demo documents installed. For this please have a look at:

`png/dev_server_schema_update/README.md` in the schema repository.

- [ ] readme makes sense / need updates?
- [ ] setup script works and UI looks like before

### CODE REVIEW

**Review by roxy-dao — COMMENTED** [review]
Looks good, thanks~

Just a few comments for the schema repo... 
- Docs should probably state that the yaml file needs to be uncommented.
- `In Setup: Make sure that you call yarn in the root directory.` I'm unsure what this is referring to...
- `In Usage`: Probably should state that you need to be in the right directory to run the ./ command
- Make a note that sync won't work anymore?

I'm still unclear how you `develop` schemas/ui schemas and have it in the central DB if sync doesn't work...

UI seems to work fine, though I do get this on the create patient modal (still lets you create a patient though, so not sure if it's worth looking into right now)
Screenshot 2023-04-13 at 2 03 51 PM

EDIT: Ran 4d init code on fresh DB, and the document permissions aren't coming through to remote... The code is there but they don't seem to be in central either

**Comment by clemens-msupply** [comment]
Thanks I updated the Readme which should hopefully answer your questions.

So to update the 4d server use the 4d init script...

When running the dev script, the program permissions from the central server are removed and updated by the script...

**Comment by CarlosNZ** [comment]
Been playing around with a fresh datafile (demo_data) and empty omsupply database, and noticed a few things.

- After running the initialisation script, there is still no "Dispensary" section visible on the main menu.
- Sync doesn't seem to be working properly. omSupply is saying 454 records to push, but when I push the manual "Sync" button, nothing happens. Server logs:  
```
2023-04-14 13:34:55.901338 INFO service::sync::sync_status::logger - Sync started
2023-04-14 13:34:55.901348 WARN service::sync::synchroniser - Sync is disabled, skipping  service/src/sync/synchroniser.rs:137
```
- Not sure when to use the 4dInit script, vs just syncing to mSupply from omSupply. Can you add some explanation of when/why this script is required? Also, after running the script, I can't see any `init_hiv_data()` method in mSupply (nor can I access the Footrunner window, so you might want to put some info, or refer to existing documentation, of how to do that).

**Comment by roxy-dao** [comment]
> * After running the initialisation script, there is still no "Dispensary" section visible on the main menu.
- Central Store has to be a dispensary

> * Sync doesn't seem to be working properly. omSupply is saying 454 records to push, but when I push the manual "Sync" button, nothing happens. Server logs:
- I think it says in the docs that you can no longer sync with the initialisation script

**Comment by clemens-msupply** [comment]
@roxy-dao and @CarlosNZ I think this is working for you now? can I merge?

**Comment by CarlosNZ** [comment]
> @roxy-dao and @CarlosNZ I think this is working for you now? can I merge?

Yeah, I think this side of things is fine. We can make small adjustments to the schema repo if we need to. 👍

**Comment by clemens-msupply** [comment]
cool than I copy existing schemas over to the schema repo now and merge this one, i.e. remove the schemas from the feature branch.

**Comment by roxy-dao** [comment]
> @roxy-dao and @CarlosNZ I think this is working for you now? can I merge?

I still don't understand what the purpose of this is... but the bash script is working (Permissions in the 4d script is still incorrect though...)

**Comment by clemens-msupply** [comment]
> > @roxy-dao and @CarlosNZ I think this is working for you now? can I merge?
> 
> I still don't understand what the purpose of this is... but the bash script is working (Permissions in the 4d script is still incorrect though...)

What do you mean? we need to be able to develop the schemas out of the main repository, i.e. we need an alternative way to quickly test and update schemas on the remote_server and we need to be able to init the 4d server with the new schema data.

**Comment by CarlosNZ** [comment]
> What do you mean? we need to be able to develop the schemas out of the main repository, i.e. we need an alternative way to quickly test and update schemas on the remote_server and we need to be able to init the 4d server with the new schema data.

Not sure for @roxy-dao, but I think I was confused why the schema data didn't sync from omSupply server (updated using script) to 4D server using normal sync process.

**Comment by roxy-dao** [comment]
> > What do you mean? we need to be able to develop the schemas out of the main repository, i.e. we need an alternative way to quickly test and update schemas on the remote_server and we need to be able to init the 4d server with the new schema data.
> 
> Not sure for @roxy-dao, but I think I was confused why the schema data didn't sync from omSupply server (updated using script) to 4D server using normal sync process.

Yes, the exact thing I'm confused about.

**Comment by clemens-msupply** [comment]
Thats a safety mechanism that Andrei build into the import cli command. For example, if you have an production system you don't want to overwrite local changes and then sync them to central... But agree, for development it might be useful to sync anyway.

**Pull request merged**
