### PR TITLE
Use browser autocomplete for inbound shipment batch input

### PR DESCRIPTION
**Pull request by andreievg**
This is a draft PR for https://github.com/openmsupply/open-msupply-internal/issues/13.

The browser behaviour for this is a bit janky and it doesn't seem to work in firefox. Sometimes the batch is remembered, other times it's not, sometimes it is remembered straight away sometimes it takes awhile, i was trying to figure out what conditions, but couldn't really find any logic.  

This functionality feels like a good candidate for a plugin/customisation, I just wanted to show how far I got

### CODE REVIEW

**Comment by mark-prins** [comment]
I had to add a form (see c73b40b85) for this to work at all for me.
With the form around it, the autofill works in chrome - so could be worth adding in?

As far as I can tell, firefox stores the input value only when the form is submitted - and we aren't submitting a form. Played around with adding a submit type on the button and then submitted using a ref.. but no beans.

**Comment by andreievg** [comment]
@mark-prins I just changed this from draft to normal PR, if it's working ok it sounds like it's good to add. It's a bit tricky to document and I think might need to be revisited, i have a feeling it can be one of those 'features' that's `forgotten` and hard to explain

**Comment by mark-prins** [comment]
@andreievg yep - it looks good. I think it would be good to merge in. agree about documentation.. I wonder if an inline code comment will be enough for now? we just need a reminder why the bits are in place I think.

and yes, may need to revisit.. it is pretty cool when it works though. and might actually be helpful 🤷 
If nothing else.. it will make testing a bit easier, I won't have to type in batches so much now

**Review by mark-prins — APPROVED** [review]
👍  works for me!

**Comment by andreievg** [comment]
>  I wonder if an inline code comment 

Good point, added: 24a9cd7e4a1bf42f6fac410e3cbe753983280493

**Pull request merged**
